# Generated by Django 3.2.7 on 2021-09-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cuenta', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=50)),
                ('nombre_completo', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
